- packages/kiwi-core/src/Accordion/index.js
- packages/kiwi-core/src/AvatarGroup/index.js
- packages/kiwi-core/src/Breadcrumb/index.js
- packages/kiwi-core/src/ButtonGroup/index.js
- packages/kiwi-core/src/InputGroup/index.js
- packages/kiwi-core/src/Menu/MenuOption.js
- packages/kiwi-core/src/Popover/index.js
- packages/kiwi-core/src/Stack/index.js
- stories/26-Menu.stories.js
- stories/27-Popover.stories.js
Hey @codebender828  as you  know there was an issue with storybook. It's because of whitespaces. https://vue-loader.vuejs.org/options.html#compileroptions 
But we should be filtering vnodes anyway. 
Fixed Components and Stories:
- Accordion
- Button Group
- Popover
- Menu Option
- Stack
- Breadcrumb
- Avatar Group
- Input Group
I've also fixed some missing imports in stories. All stories work now 🚀
before - after :
> fix: filter empty slots and update storybooks

- .storybook/config.js
- packages/docs/components/components.js
- packages/kiwi-core/src/Input/index.js
- packages/kiwi-core/src/List/index.js
- packages/kiwi-core/src/Tabs/index.js
- packages/kiwi-core/src/Tabs/tabs.styles.js
- packages/kiwi-core/src/Textarea/index.js
- packages/kiwi-core/src/index.js
- src/App.vue
- src/main.js
- stories/52-Textarea.stories.js
- stories/53-List.stories.js
- stories/54-Tabs.stories.js
> component: tabs

- packages/chakra-ui-core/src/AlertDialog/tests/AlertDialog.test.js
- packages/chakra-ui-core/src/AlertDialog/tests/__snapshots__/AlertDialog.test.js.snap
- packages/chakra-ui-core/src/Drawer/tests/Drawer.test.js
- packages/chakra-ui-core/src/Drawer/tests/__snapshots__/Drawer.test.js.snap
- packages/chakra-ui-core/src/Modal/index.js
- packages/chakra-ui-core/src/Modal/tests/Modal.test.js
- packages/chakra-ui-core/src/Modal/tests/__snapshots__/Modal.test.js.snap
Hey!
- changed modal header `div` to `header`
- mocked `Toast` since we dont need it in snapshots
- fixed modal aria labels
- fixed alertdialog aria labels
- added aria tests for drawer component
> modal drawer and alertdialog aria tests

- packages/chakra-ui-docs/router.js
Added the functionality for all docs pages to scroll to top
By default while navigating to docs pages, the pages don't start from the top if you have scrolled before(Not quite a good UX)
> fix: made sure pages always starts from top when navigating

- packages/chakra-ui-docs/docs/with-nuxt.mdx
The CButton component is missing an import in the example vue component, but is used in the template tag. 
Just a little hiccup I encountered when getting up and running with Nuxt.
Tested and works.
> docs: Add missing CButton component import in nuxt doc

- packages/chakra-ui-core/src/CNumberInput/CNumberInput.js
Fix number-input ids created at build time
NumberInput ids are created at build time and not at component initialization. This PR fixes that by removing the default property for the input prop.
fixes #184
> fix(cnumberinput): fix number-input ids created at build time

- packages/chakra-ui-docs/docs/color-mode.mdx
Update a typo error on line 12 in color-mode.mdx file. It should be "the current color mode value" not "teh current color mode value".
> fix: A typo error in color-mode.mdx file

- packages/chakra-ui-core/src/CAlert/accessibility.md
Proper aria documentation link for alert is needed
which now changed from accordion to alert in Calert Accessibility.md
Modified the url for aria documentation website.
Modifications: **From** https://www.w3.org/TR/wai-aria-practices-1.2/#accordion **to** https://www.w3.org/TR/wai-aria-practices-1.2/#alert
It will help user to redirect at correct location of aria documentation website. 
Tested by visiting the existing remote branch, and now it's getting redirected to it's proper location.
Just a typo fix in Accessibility.md file of CAlert Component.
> fix: aria documentation link modified

- packages/chakra-ui-core/src/CLink/accessibility.md
Accessibility.md file added for CLink Component
Accessibility.md file added for CLink Component, based on aria document provided into [aria link docs] (https://www.w3.org/TR/wai-aria-practices-1.2/#link)
To provide a basic idea of accessibility features that are provided in CLink component.
By Reviewing the Accessibility file in local branch
> Accessibility info added for Clink component

- website/pages/box.mdx
Fixes misspelled transform attribute in [Box docs](https://vue.chakra-ui.com/box).
`sransform` should be `transform`
> docs: fix misspelled transform attribute

- website/components/FileContributors.vue
Fix "Edit this page on GitHub" link at the end of docs page.
The "Edit this page on GitHub" link at the end of docs page leads to 404 page not found on GitHub.
Issue #278
> Docs: Fix "Edit this page" Link

- packages/chakra-ui-core/src/CReset/CReset.js
Providing a config prop to `CReset` results in `[Vue warn]: Invalid prop: type check failed for prop "config". Expected Object, got Function` when a Function is passed in.
Changed config prop type from `Object` to `Function`.
Resolves Issue: #283 
No testing included.
> fix: CReset config prop type

- packages/nuxt-chakra/lib/plugin.js
Centralizes theme in the `theme` constant instead of duplicating output into prototype and directive. Also, saves extra uses of JSON.stringify.
Simplifies applied theme look at chakra.js file and saves some extra JSON.stringify uses.
Tested into a pure Nuxt+Chakra application.
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] My code follows the code style of this project.
- [ X ] All new and existing tests passed.
> chore(theme): Simplifying chakra.js structure

- packages/nuxt-chakra/example/pages/index.vue
Injecting $chakraTheme into index.vue
It fixes a bug found on `computed` section when setting `theme()` which was returning '$chakraTheme' is not a function.
It's required to fix '$chakraTheme is not a function' on `theme` inside computed section.
Tested in a pure Nuxt+Chakra installation.
> fix(example): Injecting $chakraTheme

- packages/chakra-ui-core/CHANGELOG.md
- packages/chakra-ui-core/package.json
- packages/chakra-ui-core/src/CFlex/CFlex.stories.js
- packages/chakra-ui-core/src/config/props/props.js
Closes #303 
Includes missing style props for the following utilities:
```
flex-shrink
border-top-left-radius
border-top-right-radius
border-bottom-left-radius
border-bottom-right-radius
```
I still haven't yet found a way to test style properties. Rather than include tests for these on this pull request, I think we should have a specific convention first. Let me know if you have any thoughts about this.
> feat: include style props for flex grow and native border radius props

- .storybook/config.js
- packages/chakra-ui-core/src/CReset/CReset.js
- packages/chakra-ui-core/src/CReset/tests/CReset.test.js
- packages/chakra-ui-core/src/CReset/tests/__snapshots__/CReset.test.js.snap
Closes #312 
Includes font family to global styles for `CReset` component.
This includes the `font-family` provided to theme object.
```js
// In main.js
import Vue from "vue";
import Chakra, { CThemeProvider, CReset } from "@chakra-ui/vue";
Vue.use(Chakra, {
extendTheme: {
fonts: {
body: "'Comic Sans MS'"
}
}
});
new Vue({
el: "#app",
render: (h) =>
h(CThemeProvider, [
h(CReset) // <-- Sets root font-family from the `extendTheme` option in the Chakra plugin.
])
}).$mount();
```
> fix(creset): include font-family to global styles

- website/pages/toast.mdx
I changed danger to error on toast status valid property
The docs on toasts will be misleading as danger is not a valid property for status
Using status = 'danger' emits an error in the console but using status and displays an unstyled toast = 'error' works fine
> fix: Update toast.mdx

- website/components/AlgoliaSearch.vue
This pull request attempts to fix #336.
It gives the `AlogilaSearch` component a new stacking context.
It attempts to fix #336. 
Tested by running it locally on my machine. It doesn't touch any other components.
> docs(fix): Create a new stacking context for doc search form

- website/pages/with-vuepress.mdx
Added a new [vuepress codesandbox starter](https://codesandbox.io/s/chakra-ui-vuepress-starter-qx4up) for the vuepress chakra docs.
* Added link to codesandbox starter at the bottom of the page
* Clarified the "using chakra components" section to explain components in vuepress's theme inheritance
* Fixed a little extra `)` in the code sample
This is intended to provide a clear way to get started with ChakraUI in a new or existing Vuepress project with a live example.
The starter can successfully render basic Chakra components without completely overriding the existing Vuepress theme.
> docs: update vuepress docs with codesandbox starter

- website/pages/image.mdx
Typo in docs, Image section.
There is a typo in the docs.
There is a missing ' in this code snippet, after path-to-img.jpg.
`<c-image :src="require('@/assets/path-to-img.jpg)" />`
It's just a typo.
> docs: Add missing ' at line 80

- packages/chakra-ui-core/src/CImage/CImage.js
- packages/chakra-ui-core/src/CImage/tests/CImage.test.js
> feat(image): Add srcset support to CImage

- packages/chakra-ui-core/src/CPopper/CPopper.js
(edited) fix #414
Added a function for merging `Modifiers` of CPopper, that will merge the destination item of an array of modifiers into the corresponding (i.e. having the same `name`) item of the source array of modifiers, with `_.merge()`
The original `_.merge()` does never know which item of the destination array should be merge into an item of the source array, but simply merge them according to the order.  For example: 
```js
merge(
[
{ name: "preventOverflow", options: { boundary: "window", }, },
{ name: "offset", options: { offset: [0, 10], }, },
{ name: "arrow", options: { element: "[data-popper-arrow]", transform: "rotate(45deg)", }, },
],
[
{ name: "offset", options: { offset: [0, 20], }, },
]
)
```
should be merged into
```js
[
{ name: 'preventOverflow', options: { boundary: …
```
> fix: make CPopper's modifiers to be correctly merged

- packages/chakra-ui-core/src/CGrid/CGrid.js
- packages/chakra-ui-core/src/CGrid/CGrid.stories.js
- packages/chakra-ui-core/src/CGrid/index.js
- packages/chakra-ui-core/src/CGrid/test/CGrid.test.js
- packages/chakra-ui-core/src/CGrid/test/__snapshots__/CGrid.test.js.snap
- packages/chakra-ui-core/src/CSimpleGrid/CSimpleGrid.js
- packages/chakra-ui-core/src/index.js
- website/pages/grid.mdx
Create a `CGridItem` [like so ](https://chakra-ui.com/docs/layout/grid#griditem-props)
Adds `CGridItem`, modifies some imports/exports of `CGrid`
Consistency with the react lib and greater control over grid items using Chakra consistent props
- Storybook
- Added new tests
> feat: Adds CGridItem

- website/pages/grid.mdx
Fixes my poorly written example
> fix: grid item example

- .changeset/tall-forks-do.md
- packages/chakra-ui-core/src/CButton/CButton.js
- packages/chakra-ui-core/src/CEditable/CEditable.js
- packages/chakra-ui-core/src/CLink/CLink.js
- packages/chakra-ui-core/src/CMenu/CMenu.js
- packages/chakra-ui-core/src/CMenu/CMenuOption.js
- packages/chakra-ui-core/src/CModal/CModal.js
- packages/chakra-ui-core/src/CPopover/CPopover.js
- packages/chakra-ui-core/src/CPopover/CPopover.stories.js
- packages/chakra-ui-core/src/CRadioButtonGroup/CRadioButtonGroup.js
- packages/chakra-ui-core/src/CSlider/CSlider.js
- packages/chakra-ui-core/src/CStack/CStack.js
- packages/chakra-ui-core/src/CStack/tests/CStack.test.js
- packages/chakra-ui-core/src/CStack/tests/__snapshots__/CStack.test.js.snap
- packages/chakra-ui-core/src/CTabs/CTabs.js
- packages/chakra-ui-core/src/CTooltip/CTooltip.js
- website/pages/editable.mdx
- website/pages/menu.mdx
- website/pages/tooltip.mdx
fix: changes the `tabIndex` attribute to `tabindex`
fix: stack should be able to accept empty children
Closes #454
Closes #425
> fix: changes the `tabIndex` attribute to `tabindex`

- .changeset/dull-rats-sort.md
- packages/chakra-ui-core/src/CButton/utils/button.props.js
Fixes props validator issue with CBotton component, when variant set to “unstyled".
> fix: add an unstyled variant to the c-button validators

- .changeset/dull-books-judge.md
- packages/chakra-ui-core/types/component.d.ts
We notices that the type definitions do not include CGridItem, which leads to false error messages in the IDE although everything works when run.
> fix: Include CGridItem in type definitions

- packages/chakra-ui-core/src/utils/icons.js
FontAwesome duotone icons require multiple path elements, as well as className defs, and a default style def for the opacity of fa-secondary.
Inspecting the duotone SVGs in the pro repo, the order is `path.fa-secondary -> path.fa-primary`. I'm also not 100% sure that the grouping (`g.fa-group`) is needed, and welcome any feedback.
see #495
Tested via a local link `npm link /path/to/fork`, and checked the behavior in the browser.
Here is example output
```html
<svg data-chakra-component="CIcon" viewBox="0 0 640 512" role="presentation" class="css-5ffdf css-3vopgu css-0">
<g class="fa-group">
<defs>
<style>.fa-secondary{opacity:.4}</style>
</defs>
<path d="OMMITTED" fill="currentColor" class="fa-secondary"></path>
<path d="OMMITTED" fill="currentColor" class="fa-primary"></path>
</g>
</svg> …
```
> fix: support multiple paths in icons

- packages/chakra-ui-core/src/CInputGroup/CInputGroup.js
I pass down the listeners of cinput components using the `on` option of the data object
it fixes issue: https://github.com/chakra-ui/chakra-ui-vue/issues/292
I tested my changes using `yarn storybook` and listening for the keypress event on the first event 
of the **With left and right addons** story of CInput
All unit test also where run before pushing my changes
> fix: emit CInput events from inside a CInputGroup

- .changeset/large-birds-add.md
- packages/chakra-ui-core/src/CMenu/CMenu.stories.js
- packages/chakra-ui-core/src/CMenu/CMenuOption.js
- packages/chakra-ui-core/src/utils/icons.js
The documentation says `CMenuOptionGroup` accepts a string, number, Array as a value of the `:value` attribute. However, when the array is passed, a warning is thrown in the console:
`Invalid prop: type check failed for prop "value". Expected String, Number, got Array`
However, the component itself works as expected.
This PR fixes the error and allow the value prop to be passed as an array.
Fixes #497 
I tested with Storybook and the error wasn't displayed on the console when the fix was applied
> fix(menu): allow menu option group to use array prop

- packages/chakra-ui-nuxt/lib/plugin.js
Import `mode` from '@chakra-ui/vue'
Fix #500 
Previously when using `$mode` in @chakra-ui/nuxt: https://codesandbox.io/s/nifty-monad-8lyvj?file=/pages/index.vue:409-543
Fixed: https://codesandbox.io/s/chakra-ui-nuxt-demo-forked-gxw0m?file=/pages/index.vue:409-543
> fix: mode is not defined

- packages/chakra-ui-core/src/CToast/CToast.d.ts
Refering to https://github.com/codebender828/breadstick#-using-different-positions, the type definition of CToast does not include all options.
Include all position values in CToast
> fix: Include all position values in CToast

- package.json
- packages/chakra-ui-nuxt/lib/module.js
- packages/chakra-ui-nuxt/package.json
- yarn.lock
Bump defu to v6.0.0
Add `defu` as peerDependency to fix an error generated with the default `create-nuxt-app` command.
Fix the experience of a new user creating a project using the `create-nuxt-app` command.
Fix #531
Yes, the fix is required to run a clean up project.
> chore(deps): add defu as peerDependency

- .storybook/components/Canvas.vue
Updated the layout of the `Canvas` preview for storybook
The layout is currently broken, where only the Chakra props in the components used are working, and the scoped scss in the style tag of `Canvas.vue`.
Removed the `style` tag and all css properties, and used them as props in the chakra components used, along with additional adjustments to ensure the header content doesn't overlap the rendered story content.
Ran Storybook with the changes and viewed various stories.
> fix(canvas): update storybook preview decorator

- packages/chakra-ui-core/src/CTextarea/CTextarea.js
- packages/chakra-ui-core/src/CTextarea/tests/CTextarea.test.js
- packages/chakra-ui-core/src/CTextarea/tests/__snapshots__/CTextarea.test.js.snap
I ran into a same issue as https://github.com/chakra-ui/chakra-ui-vue/issues/548
Verified that their proposed fix indeed works and added a minimal test case.
Fixes https://github.com/chakra-ui/chakra-ui-vue/issues/548
Related to changes in https://github.com/chakra-ui/chakra-ui-vue/pull/543 - like removing the `inputValue: String,` prop.
I copied and adapted test suite from CInput, and the `v-model` test failed before the change.
> Fix CTextarea not working with `v-model`

- packages/chakra-ui-core/src/CAlertDialog/CAlertDialog.js
- website/pages/alertdialog.mdx
The `AlertDialog` component's prop [leastDustructiveRef](https://vue.chakra-ui.com/alertdialog#props) should accept the same type as the `Modal` component's prop [initialFocusRef](https://vue.chakra-ui.com/modal#props).
When I pass a function that returns a ref to leastDustructiveRef, it works well but shows a prop type warning.
```
[Vue warn]: Invalid prop: type check failed for prop "leastDestructiveRef". Expected HTMLElement, Object, got Function 
```
Ran Storybook with the changes and viewed various stories.
> fix: alert dialog `leastDestructiveRef` prop type
