chakra-ui/chakra-ui-vue

docs/README.md, package.json
This commit removes Vuepress dependency and associated files and package.json scripts
Kiwi won't be needing Vuepress for its documentation
=> removed Vuepress and config

packages/kiwi-core/README.md, packages/kiwi-core/src/AlertDialog/index.js, packages/kiwi-core/src/Editable/index.js, packages/kiwi-core/src/NumberInput/index.js, packages/kiwi-core/src/index.js, src/App.vue
=> feat(editable): added editable component

README.md, packages/chakra-ui-core/CHANGELOG.md, packages/chakra-ui-core/README.md, packages/chakra-ui-core/package.json
=> Dev/docs - Update readmes for docs

packages/chakra-ui-core/src/Avatar/index.js, packages/chakra-ui-core/src/Image/index.js
Enforces image object creation only on the client. Defers in ssr context.
=> refactor(image): optimize Image and Avatar for ssr

README.md
Just a simple typo fix on the readme
=> fix(readme): typo fix

packages/chakra-ui-core/src/Button/index.js, packages/chakra-ui-core/src/Button/tests/Button.test.js, packages/chakra-ui-core/src/ThemeProvider/index.js, packages/chakra-ui-core/src/ThemeProvider/tests/ThemeProvider.test.js, packages/chakra-ui-core/src/plugin/index.js, packages/chakra-ui-docs/layouts/default.vue
Fix to preserve the button component's width when `isLoading` props is set to true.
=> fix(Button): Preserve button width on load

packages/chakra-ui-core/src/Stat/Stat.stories.js, packages/chakra-ui-core/src/Stat/index.js, packages/chakra-ui-core/src/Stat/tests/Stat.test.js, packages/chakra-ui-core/src/Stat/tests/__snapshots__/Stat.test.js.snap, packages/chakra-ui-core/src/config/props/props.js, packages/chakra-ui-core/src/index.js
Adds the Stat compound component
- Stat
- StatGroup
- StatLabel
- StatNumber
- StatArrow
- StatHelperText
Basic usage
With indicators
=> feat(Stat): adds Stat component

packages/chakra-ui-docs/docs/button.mdx, packages/chakra-ui-docs/layouts/default.vue, packages/chakra-ui-docs/router.js
Added docs for Button component
=> Added docs for Button component

packages/chakra-ui-docs/docs/alert.mdx
Documentation for Alert component
=> docs: documentation for Alert component

packages/chakra-ui-docs/docs/alert.mdx, packages/chakra-ui-docs/layouts/default.vue
=> docs(alert): added alert docs

packages/chakra-ui-core/src/CAlert/CAlert.stories.js, packages/chakra-ui-core/src/CAlert/tests/CAlert.test.js, packages/chakra-ui-core/src/CAlert/tests/__snapshots__/CAlert.test.js.snap, packages/chakra-ui-core/src/CAlert/utils/alert.styles.js, packages/chakra-ui-core/src/CToast/CToast.stories.js
Fixes #94 
- Normalizes all variant names to be `kebab-case`.
- Added variant snapshot tests.
- Added variant stories
=> Fixes Alert variant names

packages/chakra-ui-core/src/CAccordion/CAccordion.js, packages/chakra-ui-core/src/CAspectRatioBox/CAspectRatioBox.js
=> feat(aspectratiobox): added aspect ratio box jsdoc

packages/chakra-ui-core/src/CAlertDialog/CAlertDialog.js, packages/chakra-ui-core/src/CAlertDialog/tests/__snapshots__/CAlertDialog.test.js.snap, packages/chakra-ui-core/src/CBox/CBox.js, packages/chakra-ui-core/src/CBreadcrumb/CBreadcrumb.js, packages/chakra-ui-core/src/CBreadcrumb/accessibility.md, packages/chakra-ui-core/src/CBreadcrumb/tests/__snapshots__/CBreadcrumb.test.js.snap, packages/chakra-ui-core/src/CButton/CButton.js, packages/chakra-ui-core/src/CButton/accesibility.md, packages/chakra-ui-core/src/CButton/tests/__snapshots__/CButton.test.js.snap, packages/chakra-ui-core/src/CButtonGroup/CButtonGroup.js, packages/chakra-ui-core/src/CButtonGroup/tests/__snapshots__/CButtonGroup.test.js.snap, packages/chakra-ui-core/src/CCheckbox/CCheckbox.js, packages/chakra-ui-core/src/CCheckbox/accessibility.md, packages/chakra-ui-core/src/CCheckbox/tests/__snapshots__/CCheckbox.test.js.snap, packages/chakra-ui-core/src/CCheckboxGroup/CCheckboxGroup.js, packages/chakra-ui-core/src/CCheckboxGroup/tests/__snapshots__/CCheckboxGroup.test.js.snap, packages/chakra-ui-core/src/CDrawer/tests/__snapshots__/CDrawer.test.js.snap, packages/chakra-ui-core/src/CIconButton/tests/__snapshots__/CIconButton.test.js.snap, packages/chakra-ui-core/src/CModal/tests/__snapshots__/CModal.test.js.snap, packages/chakra-ui-core/src/CRadioButtonGroup/tests/__snapshots__/CRadioButtonGroup.test.js.snap
Adds component review for box, breadcrumb, button, buttongroup, checkbox and checkboxgroup
=> add review for box, breadcrumb, button, buttongroup, checkbox and checkboxgroup

packages/chakra-ui-core/src/CAlertDialog/CAlertDialog.js, packages/chakra-ui-core/src/CAlertDialog/tests/__snapshots__/CAlertDialog.test.js.snap, packages/chakra-ui-core/src/CBadge/CBadge.js, packages/chakra-ui-core/src/CBadge/CBadge.stories.js, packages/chakra-ui-core/src/CBadge/tests/CBadge.test.js, packages/chakra-ui-core/src/CBadge/tests/__snapshots__/CBadge.test.js.snap, packages/chakra-ui-core/src/CBox/CBox.js, packages/chakra-ui-core/src/CBreadcrumb/CBreadcrumb.js, packages/chakra-ui-core/src/CBreadcrumb/accessibility.md, packages/chakra-ui-core/src/CBreadcrumb/tests/__snapshots__/CBreadcrumb.test.js.snap, packages/chakra-ui-core/src/CButton/CButton.js, packages/chakra-ui-core/src/CButton/accesibility.md, packages/chakra-ui-core/src/CButton/tests/__snapshots__/CButton.test.js.snap, packages/chakra-ui-core/src/CButtonGroup/CButtonGroup.js, packages/chakra-ui-core/src/CButtonGroup/tests/__snapshots__/CButtonGroup.test.js.snap, packages/chakra-ui-core/src/CCheckbox/CCheckbox.js, packages/chakra-ui-core/src/CCheckbox/accessibility.md, packages/chakra-ui-core/src/CCheckbox/tests/__snapshots__/CCheckbox.test.js.snap, packages/chakra-ui-core/src/CCheckboxGroup/CCheckboxGroup.js, packages/chakra-ui-core/src/CCheckboxGroup/tests/__snapshots__/CCheckboxGroup.test.js.snap, packages/chakra-ui-core/src/CDrawer/tests/__snapshots__/CDrawer.test.js.snap, packages/chakra-ui-core/src/CIconButton/tests/__snapshots__/CIconButton.test.js.snap, packages/chakra-ui-core/src/CModal/tests/__snapshots__/CModal.test.js.snap, packages/chakra-ui-core/src/CRadioButtonGroup/tests/__snapshots__/CRadioButtonGroup.test.js.snap, packages/chakra-ui-core/src/config/props/props.js, packages/chakra-ui-docs/docs/box.mdx
=> docs(box): added box docs

packages/chakra-ui-docs/docs/tooltip.mdx
Documentation for CTooltip component
=> docs: added documentation for CTooltip component

packages/chakra-ui-docs/docs/tag.mdx
Documentation for tag component
=> docs: documentation for tag component

packages/chakra-ui-docs/docs/progress.mdx
Documentation for the Progress Component
=> docs: documentation for the progress component

packages/chakra-ui-docs/docs/spinner.mdx
Documentation for the Spinner component
=> docs: documentation for spinner component

packages/chakra-ui-docs/docs/stat.mdx
Documentation for the Stat component
=> docs: documentation for the stat component

README.md
Current link to contributors guide is broken. This PR fixes that.
=> Fix link to contributors guide

packages/chakra-ui-docs/docs/stack.mdx
Documentation for the Stack component.
=> docs(stack.mdx): documentation for the Stack component

packages/chakra-ui-docs/docs/simplegrid.mdx
Documentation for SimpleGrid component.
=> docs(simplegrid.mdx): documentation for SimpleGrid component

packages/chakra-ui-docs/docs/switch.mdx
=> docs: documentation for the Switch component

packages/chakra-ui-docs/docs/text.mdx
Documentation for the Text component
=> docs: documentation for the Text component

packages/chakra-ui-docs/docs/select.mdx
Documentation for the Select component.
=> docs(select.mdx): documentation for the Select component

packages/chakra-ui-docs/docs/slider.mdx
Documentation for the Slider component.
=> docs(slider.mdx): documentation of the Slider component

packages/chakra-ui-docs/docs/textarea.mdx
Documentation for the Textarea component
=> docs(textarea.mdx): documentation of the Textarea component

packages/chakra-ui-core/src/CNumberInput/CNumberInput.js
Implement v-model on the component
- Added a model option
- Set the event to emit or update the props
This allows the local state to keep track of changes on the component
fixes #150
=> fix: implement v-model on CNumberInput component

README.md, packages/chakra-ui-core/src/CNumberInput/CNumberInput.js, packages/chakra-ui-core/src/CNumberInput/CNumberInput.stories.js, packages/chakra-ui-core/src/CPopover/CPopover.js, packages/chakra-ui-core/src/CPopover/CPopover.stories.js, packages/chakra-ui-core/src/CRadio/CRadio.js, packages/chakra-ui-core/src/CRadio/CRadio.stories.js, packages/chakra-ui-core/src/CRadioButtonGroup/CRadioButtonGroup.js, packages/chakra-ui-core/src/CRadioButtonGroup/CRadioGroup.stories.js, packages/chakra-ui-core/src/CRadioButtonGroup/tests/CRadioButtonGroup.test.js, packages/chakra-ui-core/src/CRadioButtonGroup/tests/__snapshots__/CRadioButtonGroup.test.js.snap, packages/chakra-ui-core/src/CRadioGroup/CRadioGroup.js, packages/chakra-ui-core/src/CTabs/CTabs.stories.js, packages/chakra-ui-docs/docs/radio.mdx
Implements `v-model` for `CRadioButtonGroup` and `CRadioGroup`
Closes #159 
Closes #158 
Closes #154
=> Implements `v-model` for `CRadioButtonGroup` and `CRadioGroup`

packages/chakra-ui-core/src/CCollapse/CCollapse.stories.js, packages/chakra-ui-docs/docs/collapse.mdx
Document easing props for CCollapse
Adds documentation of easing prop to CCollapse component.
closes #144
=> Document easing props for CCollapse

packages/chakra-ui-core/src/CSlider/CSlider.js
Implements v-model (two-way binding) for this component
To keep track of the user's action
fixes #151
=> Implement vmodel on cslider component

packages/chakra-ui-docs/docs/accessibility.mdx, packages/chakra-ui-docs/docs/constraint-based-design.mdx, packages/chakra-ui-docs/docs/contributing.mdx
=> docs: fixed typos in about Chakra UI section

packages/chakra-ui-docs/docs/getting-started.mdx
Added docs for using the Chakra UI's Vue CLI plugin
=> docs: added docs for using Chakra UI Vue CLI plugin

packages/chakra-ui-docs/package.json, packages/chakra-ui-docs/plugins/analytics.js
=> chore: catch docs token error

packages/chakra-ui-docs/plugins/analytics.js
=> fix: use env context

README.md, packages/chakra-ui-docs/utils/all-routes.js
fixes #189  
-  statically generate contributors page during deployment
- fix contributor anchor in README to scroll to contributors section
=> Broken contributors link

packages/chakra-ui-docs/docs/with-nuxt.mdx, yarn.lock
=> docs(with-nuxt.mdx): fix typo in with-nuxt.mdx

packages/chakra-ui-docs/components/Navbar.vue
Added a link to Chakra UI React website - Fixes #207
=> docs: Add Link to React Website

package.json, packages/chakra-ui-core/CHANGELOG.md, packages/chakra-ui-core/package.json, packages/chakra-ui-core/src/CBox/index.js, packages/chakra-ui-core/src/Chakra/index.js, packages/chakra-ui-core/src/directives/chakra.directive.js, packages/chakra-ui-core/src/directives/chakra.stories.js, packages/chakra-ui-core/src/directives/index.js, packages/chakra-ui-core/src/utils/strings.js, packages/chakra-ui-docs/CHANGELOG.md, packages/chakra-ui-docs/components/BottomLink.vue, packages/chakra-ui-docs/components/Hero.vue, packages/chakra-ui-docs/components/Navbar.vue, packages/chakra-ui-docs/nuxt.config.js, packages/chakra-ui-docs/package.json, packages/chakra-ui-docs/pages/v-chakra.mdx, packages/chakra-ui-docs/utils/all-routes.js, packages/nuxt-chakra/CHANGELOG.md, packages/nuxt-chakra/example/nuxt.config.js, packages/nuxt-chakra/example/pages/directive.vue, packages/nuxt-chakra/example/pages/index.vue, packages/nuxt-chakra/jest.config.js, packages/nuxt-chakra/lib/module.js, packages/nuxt-chakra/lib/plugin.js, packages/nuxt-chakra/package.json, packages/nuxt-chakra/test/module.spec.js, yarn.lock
This pull request implements the `v-chakra` directive implemented in #230
Closes #230 
**Base usage - No arguments**
```vue
<div v-chakra p="3" color="red.400" font-weight="bold">
Welcome to Chakra directive
</div>
```
**With value - Styles object**
```vue
<div v-chakra="{
p: 3,
shadow: 'sm',
h1: {
bg: 'blue.100'
},
}">
<h1>Title</h1>
<p>Text</p>
</div>
```
**With value - Function**
```vue
<div v-chakra="theme => ({
shadow: 'sm',
bg: theme.colors.blue[800],
color: theme.colors.yellow[300],
p: {
fontWeight: 'bold',
p: 3
}
})">
<p>Computed styles</p>
</div>
```
**Example Demo Button**
```vue
<button v-chakra="{
':hover': { bg: 'green.400' },
':focus': { shadow: 'outline' }
}" font-weight="bold" px="4" py="3" color="white" rounded="md" bg="blue.400" outline="none">
Button
</button>
```
=> `v-chakra` directive

packages/chakra-ui-docs/pages/radio.mdx
fix a typo in packages/chakra-ui-docs/pages/radio.mdx
- [x ] Bug fix (non-breaking change which fixes an issue)
=> docs: fix typos

packages/chakra-ui-docs/pages/radio.mdx
=> docs(radio): fix typo in docs

packages/chakra-ui-core/src/CMenu/CMenu.js, packages/chakra-ui-core/src/CMenu/CMenu.stories.js, packages/chakra-ui-core/src/CPopper/CPopper.js
Fixes issue with `CMenu` component closing when `closeOnBlur` prop is passed.
=> fix(menu): closeOnBlur

packages/chakra-ui-core/src/CButton/utils/button.props.js
Fixes props validator issue with CBotton component, when size set to "xs".
=> chore: Fixes props validator issue with CBotton component

packages/chakra-ui-core/src/CInput/accessibility.md
accessibility.md file added to brief the basic introductions on
accessibility of CInput component
Accessibility.md file added for CInput Component
To provide a basic idea of accessibility features that are provided in CInput component.
By Reviewing the Accessibility file in local branch and by running all the test cases.
=> Accessibility info added for CInput component

.storybook/config.js, website/components/Navbar.vue, website/plugins/chakra-ui.js
Add Discord link to documentation navbar.
This PR closes #267
=> docs: add discord invite link to navbar

website/pages/icon.mdx
modified a component attribute name in the Documentation
in the file website/pages/icon.mdx I edited the attribute names of the components c-icon in line 145 & 146 from icon="" to name=""
This Change is required to fix issues regarding the clarity of the documentation. I'm learning chakra and I had trouble finding the issue although I followed the documentation to the letter. until I found randomly that the correct attribute is "name"
tested in a Linux Environment, in a docker container Docker version 19.03.12, build 48a66213fe _node:12.18.3-stretch-slim_ in a nuxtjs project
=> Docs(Icon): Fix Mistake in Documentation

package.json
Add `cross-env` to accommodate Windows developers
This pull request will add a new tooling dependency `cross-env`, which will be called on `storybook` script
`storybook` script will throw an error if the script is executed on OS doesn't natively support setting environment variables. Unfortunately, Windows as one of the popular OS doesn't support this.
Will fix #277
Tested by running `storybook` script on my Windows 10 build 1909 machine. The script runs flawlessly.
=> chore(deps): Add cross-env to accommodate Windows machines

.github/semantic.yml
This pull requests establishes a set of guidelines for pull requests to ensure that PR and commit messages are semantic. This makes it convenient for reviewers and other contributors to understand what happens in each commit.
This PR will also loosed the commit thread condition to accept Merge commit messages and at least on e semantic commit message.
Below is the introduced configuration:
```yml
titleOnly: true
anyCommit: true
allowMergeCommits: true
allowRevertCommits: true 
```
For more information, see Semantic PR docs: https://github.com/zeke/semantic-pull-requests
=> chore(semantic): modify rules for semantic pull requests

website/components/MDXComponents.js, website/pages/modal.mdx
fix: move is-centered prop to CModal compoennt in docs
Closes #290 #291
=> fix: overflow scrolling on mobile view tables in documentation

.changeset/pre.json, .changeset/wise-donkeys-buy.md, packages/chakra-ui-core/CHANGELOG.md, packages/chakra-ui-core/package.json, packages/chakra-ui-core/src/CSwitch/CSwitch.js, packages/chakra-ui-core/src/CSwitch/CSwitch.stories.js, packages/chakra-ui-core/src/CSwitch/tests/CSwitch.test.js, packages/chakra-ui-core/src/utils/vdom.js, packages/nuxt-chakra/CHANGELOG.md, packages/nuxt-chakra/package.json, website/CHANGELOG.md, website/package.json
Closes #293 
Fixes issue where `v-model` broken when the use of the `@change` event handler is employed for the `CSwitch`
Also included tests to ensure it works.
View demo: https://deploy-preview-295--chakra-ui-vue.netlify.app/?path=/story/ui-switch--with-v-model-change
=> fix: CSwitch v-model works combined with `@change` event handler

packages/chakra-ui-core/src/CRadio/CRadio.js
I changed props.value from String to [String, Number]
CRadio logs error to the console when value is a Number instead of String.
The documentation already says Number is valid.
=> fix: Update CRadio props.value

website/pages/stack.mdx
=> docs: update stack.mdx

website/pages/list.mdx
Fixed attribute name from camel to kebab case.
=> docs: update list.mdx

website/pages/icon.mdx
Added a small part under the use of 'Using an Icon library' for the Nuxt.js configuration.
Done this by using the Git edit tool.
I was missing this information when adding an Icon library in my Nuxt.js project
=> docs: update icon.mdx with Nuxt.js option

packages/chakra-ui-core/src/CInputGroup/CInputGroup.js, packages/chakra-ui-core/src/CInputGroup/tests/CInputGroup.test.js, packages/chakra-ui-core/src/CInputGroup/tests/__snapshots__/CInputGroup.test.js.snap, website/components/MDXComponents.js, website/layouts/default.vue
=> fix(inputgroup): default inputgroup z-index to containing element zindex

website/pages/menu.mdx
=> docs: fixed attributes from camel to kebab case

website/pages/button.mdx
Fixed camelCase to kebab-case.
=> docs: update button.mdx

website/pages/extending-theme.mdx
Added a small part under the use of 'extending-theme' for the Nuxt.js configuration.
I was missing this information when using the Theme Object in my Nuxt.js project
=> docs: 📚 Add Nuxt option information for extending theme

.github/workflows/release.yml
=> chore: improve ci workflow

packages/chakra-ui-nuxt/lib/module.js
Changed params for the parsePackIcons function to only options.icons.iconSet.
TODO:
Fix tests (also got errors in other tests when pushing the code)
This should fix the issue were icons from external icon libraries didn't get added.
=> fix(nuxt): fix params for parsePackIcons function

website/pages/color-mode.mdx
=> docs(*): 📚 Add missing comma in colorMode import

.all-contributorsrc, .changeset/config.json, .changeset/loud-pianos-argue.md, README.md, packages/chakra-ui-core/src/CCloseButton/CCloseButton.js, packages/chakra-ui-core/src/CCloseButton/utils/closebutton.props.js, website/pages/image.mdx, website/pages/with-vuepress.mdx
Fix release candidate for v0.8.1 🎉
Includes changes from:
#417 
#416 
#410
=> chore: release candidate for v0.8.1 🎉

website/pages/accordion.mdx
=> fix(docs): Reveals accordion opening hidden by comment

.changeset/old-crews-share.md
chore: version phantom release to create tags on GitHub
=> chore: version phantom release
